"""empty message

Revision ID: cae6518de02b
Revises: 1b514d4e8b9c
Create Date: 2022-11-27 10:32:39.632608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae6518de02b'
down_revision = '1b514d4e8b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('payment_page_slug', sa.String(), nullable=False),
    sa.Column('payment_page_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('address'),
    sa.UniqueConstraint('payment_page_id'),
    sa.UniqueConstraint('payment_page_slug')
    )
    op.drop_table('examples')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wallet')
    # ### end Alembic commands ###
